apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.8.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: oracle-mysql
    addon.kubeblocks.io/provider: ApeCloud
    addon.kubeblocks.io/version: 0.1.0
  name: oracle-mysql
spec:
  description: MySQL is a widely used, open-source relational database management system (RDBMS).
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/152630/packages/helm/stable/charts/oracle-mysql-0.1.0.tgz
    installValues:
      setValues:
        - "image.registry=docker.io"
  defaultInstallValues:
  - enabled: false
  type: Helm